# Generated by Django 4.2.7 on 2025-10-10 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=10)),
                ('timeframe', models.CharField(max_length=10)),
                ('period', models.IntegerField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('confidence_level', models.IntegerField()),
                ('market_sentiment', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prediction Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
