# Generated by Django 4.2.25 on 2025-10-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='prediction_target_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
