# Generated by Django 4.2.7 on 2025-10-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_predictionhistory_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='actual_price',
        ),
    ]
