# Generated by Django 4.2.7 on 2025-10-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_remove_predictionhistory_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
